CREATE TABLE ratings (id INTEGER PRIMARY KEY AUTOINCREMENT,
date_created TEXT NOT NULL,
user_id INTEGER NOT NULL,
absolute_uri TEXT NOT NULL,
val INTEGER NOT NULL,

FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);