DROP TABLE "caches";
CREATE TABLE "caches" (
"id" INTEGER PRIMARY KEY NOT NULL UNIQUE,
"access_count" INTEGER NOT NULL DEFAULT 1,
"access_value" REAL NOT NULL DEFAULT 0.0,
"size" INTEGER NOT NULL DEFAULT 0
);
